In [4]:
import numpy as np

In [5]:
#Créer un tableau unidimentionnel
notre_tableau = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [11]:
#Créer un tableau multi dimentionnel
mon_tableau_multidimentionel = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
mon_tableau_multidimentionel

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# Un sous ensemble est une vue du tableau unidimentionnel.
sous_tableau = notre_tableau[0:5]

In [15]:
sous_tableau

array([1, 2, 3, 4, 5])

In [16]:
# Modifier le sous tableau modifie le tableau d'origine
sous_tableau[0] = 10 
sous_tableau

array([10,  2,  3,  4,  5])

In [17]:
notre_tableau

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
# Par contre, si vous veut faire une copie ....
notre_tableau = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [19]:
# Je veux faire une copie et pas une vue !
sous_tableau = notre_tableau[0:5].copy

In [21]:
# Acceder aux valeurs  d'un array multi dimensionnel 
#Créer un tableau multi dimentionnel
mon_tableau_multidimentionel = np.array([[1,2,3],[4,5,6],[7,8,9]])
# je veux la valeur à la 2ème ligne, de la 3ème colonne ( Ca commence par 0)
mon_tableau_multidimentionel[1,2]

6

In [22]:
# je veux la valeur à la 2ème ligne, de la dernière colonne
mon_tableau_multidimentionel[1,-1]

6

In [23]:
# je veux toutes les valeurs de la 1ere colonne 
mon_tableau_multidimentionel[:,0]

array([1, 4, 7])

In [24]:
# je veux toutes les valeurs de la 1ere ligne
mon_tableau_multidimentionel[0,:]

array([1, 2, 3])

In [4]:
# Explorer et filtrer un array
# Par exemple garder que les valeurs supérieures à 2
import numpy as np
array = np.random.randint(100,size=(6,4))
array

array([[72, 79, 15, 96],
       [16, 20, 10, 58],
       [16, 51, 91, 19],
       [41, 35, 54, 31],
       [ 4, 14, 93, 88],
       [88, 96, 84, 75]])

In [8]:
# lire les Dimensions du tableau
array.ndim

2

In [9]:
# Lire le shape : 6 et lignes et 4 colonnes
array.shape

(6, 4)

In [11]:
# Lire le Type des valeurs
array.dtype

dtype('int32')

In [12]:
# Lire le Nb de valeurs
array.size

24

In [14]:
# Filtrer les valeurs supérieures à 50 du tableau 
array[array>50]

array([72, 79, 96, 58, 51, 91, 54, 93, 88, 88, 96, 84, 75])

In [15]:
# Filtrer  les valeurs booléennes du tableau > 50
array > 50 

array([[ True,  True, False,  True],
       [False, False, False,  True],
       [False,  True,  True, False],
       [False, False,  True, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [31]:
# et : &
# ou : |

# Filtrer les vals Pas égales à 50 ou supérieures à 80
array [(array < 60) | (array > 84)]

array([15, 96, 16, 20, 10, 58, 16, 51, 91, 19, 41, 35, 54, 31,  4, 14, 93,
       88, 88, 96])

In [33]:
# Concaténer les tableaux de même dimension
array1 = np.random.randint(100,size=(6,4))
array2 = np.random.randint(100,size=(6,4))
np.concatenate([array1,array2])

array([[72, 39, 28, 45],
       [ 5, 48, 94, 27],
       [31, 44, 24, 99],
       [38, 16, 67, 44],
       [84, 91, 97, 67],
       [64, 89, 17, 36],
       [49, 76, 94, 73],
       [39, 59, 16,  8],
       [63, 46, 46,  6],
       [52, 27,  2, 30],
       [24, 68, 96, 19],
       [49, 25, 98, 22]])

In [34]:
array3 = np.random.randint(100,size=(6,4))
np.concatenate([array1,array,array3])

array([[72, 39, 28, 45],
       [ 5, 48, 94, 27],
       [31, 44, 24, 99],
       [38, 16, 67, 44],
       [84, 91, 97, 67],
       [64, 89, 17, 36],
       [72, 79, 15, 96],
       [16, 20, 10, 58],
       [16, 51, 91, 19],
       [41, 35, 54, 31],
       [ 4, 14, 93, 88],
       [88, 96, 84, 75],
       [80, 49,  9, 31],
       [54, 58, 92, 84],
       [93, 38, 29, 77],
       [65, 53, 88, 80],
       [65, 99, 26, 87],
       [83, 47, 50, 10]])

In [40]:
# Concaténer  des tableaux de dimensions différentes .
array1 = np.array([15,24,34])
array2 = np.array([[1,2,3],[3,4,5],[4,5,6]])

In [41]:
np.vstack([array1,array2])

array([[15, 24, 34],
       [ 1,  2,  3],
       [ 3,  4,  5],
       [ 4,  5,  6]])

In [42]:
# Split - Cassure des tableaux de 1 dimension
array = np.array([15,16,17,12,49,52,12,14,36])

In [43]:
# On casse aux index 2 et 6
np.split(array,[2,6])

[array([15, 16]), array([17, 12, 49, 52]), array([12, 14, 36])]

In [44]:
array1,array2,array3 = np.split(array,[2,6])

In [45]:
print(array1)

[15 16]


In [55]:
# Split - Cassure des tableaux de 2 dimensions par ligne
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array1,array1bis = np.vsplit(array,[2])
print(array1)


[[1 2 3]
 [4 5 6]]
[[7 8 9]]


In [56]:
print(array1bis)

[[7 8 9]]


In [52]:
# Split - Cassure des tableaux de 2 dimensions par colonne
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array1,array1bis = np.hsplit(array,[2])
print(array1)

[[1 2]
 [4 5]
 [7 8]]


In [53]:
print(array1bis)

[[3]
 [6]
 [9]]


In [57]:
#Calculer sur un array 
import numpy as np
array = np.random.randint(100,size=(10,9))
array

array([[80, 17, 37, 45, 72, 85, 73, 79, 19],
       [65, 80, 23, 38, 22, 67, 11, 30, 40],
       [91, 39, 10, 93, 16, 14, 51, 89, 55],
       [64, 38, 29, 42, 90, 62, 33, 71, 25],
       [18, 15, 81, 43, 98, 53, 35, 23, 33],
       [98, 73, 72, 46, 64, 58, 12, 72, 88],
       [58, 37, 31, 43, 36,  5, 75, 60, 90],
       [38, 58, 90, 92, 61, 52, 35, 58,  7],
       [74, 64, 96, 36,  7, 66, 76, 19, 72],
       [36, 18,  7, 64,  4, 80, 97, 56, 35]])

In [58]:
# ajouter 2 à cahque valeurs du tab
array + 2 

array([[ 82,  19,  39,  47,  74,  87,  75,  81,  21],
       [ 67,  82,  25,  40,  24,  69,  13,  32,  42],
       [ 93,  41,  12,  95,  18,  16,  53,  91,  57],
       [ 66,  40,  31,  44,  92,  64,  35,  73,  27],
       [ 20,  17,  83,  45, 100,  55,  37,  25,  35],
       [100,  75,  74,  48,  66,  60,  14,  74,  90],
       [ 60,  39,  33,  45,  38,   7,  77,  62,  92],
       [ 40,  60,  92,  94,  63,  54,  37,  60,   9],
       [ 76,  66,  98,  38,   9,  68,  78,  21,  74],
       [ 38,  20,   9,  66,   6,  82,  99,  58,  37]])

In [59]:
# soustraire 2 à cahque valeurs du tab
array - 2

array([[78, 15, 35, 43, 70, 83, 71, 77, 17],
       [63, 78, 21, 36, 20, 65,  9, 28, 38],
       [89, 37,  8, 91, 14, 12, 49, 87, 53],
       [62, 36, 27, 40, 88, 60, 31, 69, 23],
       [16, 13, 79, 41, 96, 51, 33, 21, 31],
       [96, 71, 70, 44, 62, 56, 10, 70, 86],
       [56, 35, 29, 41, 34,  3, 73, 58, 88],
       [36, 56, 88, 90, 59, 50, 33, 56,  5],
       [72, 62, 94, 34,  5, 64, 74, 17, 70],
       [34, 16,  5, 62,  2, 78, 95, 54, 33]])

In [60]:
# Multiplier par 10 la première colonne
array[:,0]  *10

array([800, 650, 910, 640, 180, 980, 580, 380, 740, 360])

In [61]:
# MOyenne des valeurs 
np.mean(array)

51.22222222222222

In [63]:
array.max()

98

In [64]:
# Moyenne par colonne
np.mean(array, axis = 0)

array([62.2, 43.9, 47.6, 54.2, 47. , 54.2, 49.8, 55.7, 46.4])

In [65]:
# Moyenne par ligne
np.mean(array, axis = 1)

array([56.33333333, 41.77777778, 50.88888889, 50.44444444, 44.33333333,
       64.77777778, 48.33333333, 54.55555556, 56.66666667, 44.11111111])